name: Dependency Update

on:
  push:
    branches:
      - master # or 'main', or any branch(es) you want to trigger on
  schedule:
    - cron: '0 2 * * *' # runs daily at 02:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v27

      - name: Update flake.lock
        run: nix flake update

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add flake.lock
          git commit -m "chore: update flake.lock dependencies" || exit 0
          git push
