name: Dependency Update

on:
  push:
    branches:
      - master # or 'main', or any branch(es) you want to trigger on
  schedule:
    - cron: '0 2 * * *' # runs daily at 02:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Set up Nix
        uses: cachix/install-nix-action@v23

      - name: Run update script
        run: bash update-gemini.sh

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: update dependencies on push" || exit 0
          git push
